/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors from globals.css
        'outline-variant': '#c4c6cf',
        'on-surface': '#1a1c1c',
        'inverse-on-surface': '#f1f1f1',
        'primary-fixed': '#d6e3ff',
        'error': '#ba1a1a',
        'surface-variant': '#e2e2e2',
        'surface-container-low': '#f3f3f3',
        'primary-container': '#002147',
        'surface': '#f9f9f9',
        'secondary-fixed': '#ffe088',
        'on-primary-container': '#708ab5',
        'inverse-surface': '#2f3131',
        'secondary': '#735c00',
        'on-error': '#ffffff',
        'on-background': '#1a1c1c',
        'primary-fixed-dim': '#aec7f6',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001b3d',
        'on-error-container': '#93000a',
        'tertiary': '#000b19',
        'primary': '#000a1e',
        'surface-bright': '#f9f9f9',
        'surface-dim': '#dadada',
        'on-secondary-container': '#745c00',
        'inverse-primary': '#aec7f6',
        'outline': '#74777f',
        'on-tertiary-fixed': '#001d34',
        'on-secondary-fixed-variant': '#574500',
        'surface-container-high': '#e8e8e8',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#9acbff',
        'on-tertiary-fixed-variant': '#004a78',
        'on-primary-fixed-variant': '#2d476f',
        'on-surface-variant': '#44474e',
        'on-tertiary-container': '#558dc2',
        'on-primary': '#ffffff',
        'secondary-container': '#fed65b',
        'tertiary-container': '#00233d',
        'surface-container': '#eeeeee',
        'on-secondary-fixed': '#241a00',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#e9c349',
        'surface-container-highest': '#e2e2e2',
        'tertiary-fixed': '#cfe5ff',
        'surface-tint': '#465f88',
      },
    },
  },
  plugins: [],
};
